// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2209aa55-4766-476c-a892-722e6d38d91d",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "d4676b2cf7c54001a6f23dfb3006fe4c",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
